sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pranavgautam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pranavgautam/docker-react npm run test

deploy:
  provide: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-094982966113"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY